ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS phone_number;
ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS phone_verified_at;
ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS pending_phone_number;
ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS phone_otp_code_hash;
ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS phone_otp_expires_at;
ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS phone_otp_sent_at;
ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS phone_otp_attempts;
